name: 'CI: Unit'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn run build

      - name: Run tests
        run: |
          yarn run lint
          yarn run test:unit

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
