name: Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.5.1"
          cache: yarn

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - run: yarn install --forzen-lockfiles
      - run: yarn docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
